### ISSUE TITLE
Plug-in not appearing in dropdown menu

### ISSUE THREAD

**Issue by ghost** [don-philipe/transcriber#1]
I put the qml file into Musescore 3's plugins folder, then restarted Musescore. For some reason though, the plug-in isn't appearing in the plugins manager to enable. Is there anything I'm missing?

**Comment by don-philipe** [comment]
Hmm, strange. It should work as you described it. Which exact Musescore version and which OS are you using?

**Comment by ghost** [comment]
Vers 3.6.2.548021803 on Windows 10

**Comment by don-philipe** [comment]
It seems that the plugin handling is different, depending on the OS.

I'll do further investigations.

**Comment by don-philipe** [comment]
The plugin uses the QtMultimedia package which isn't part of the MuseScore installation on Windows, as I found out now. So the plugin is only usable when either compiling MuseScore with the named package, or when Qt ist installed anyways (which is the case on my Linux machine).
